# Generated by Django 3.2.5 on 2021-07-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
