# Generated by Django 3.2.5 on 2021-07-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0002_alter_servicearea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='service_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='locate.servicearea'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='locate.provider'),
        ),
    ]
