# Generated by Django 3.2.5 on 2021-07-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0003_auto_20210725_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['id']},
        ),
    ]
